# Generated by Django 5.0.4 on 2024-05-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
