# Generated by Django 5.0.4 on 2024-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_conference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymeetup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='communitymeetup_images/'),
        ),
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concert_images/'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seminar_images/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workshop_images/'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='conference_images/'),
        ),
    ]
